// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/tankbusta/gocrackdb-converter/lib/ent/runtime.go

const (
	Version = "v0.9.2-0.20211214171404-f0ca97d30968"            // Version of ent codegen.
	Sum     = "h1:yeCkgsO3CoNHiAViHZYD/pwmPss6qHp4KR4mZ2plTVU=" // Sum of ent codegen.
)
