// Code generated by entc, DO NOT EDIT.

package user

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldEmailAddress holds the string denoting the email_address field in the database.
	FieldEmailAddress = "email_address"
	// FieldIsSuperUser holds the string denoting the is_super_user field in the database.
	FieldIsSuperUser = "is_super_user"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeCreatedTasks holds the string denoting the created_tasks edge name in mutations.
	EdgeCreatedTasks = "created_tasks"
	// Table holds the table name of the user in the database.
	Table = "users"
	// CreatedTasksTable is the table that holds the created_tasks relation/edge.
	CreatedTasksTable = "tasks"
	// CreatedTasksInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	CreatedTasksInverseTable = "tasks"
	// CreatedTasksColumn is the table column denoting the created_tasks relation/edge.
	CreatedTasksColumn = "task_created_by"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldEnabled,
	FieldEmailAddress,
	FieldIsSuperUser,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
